# Generated by Django 4.1.1 on 2022-10-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablo", "0002_alter_registration_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration_user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
